import numpy.random as random


# Short Immutable Lists
power_levels = ["regular", "convergent evolution", "starter", "god", "fossil", "legendary", "pseduo legendary", "mythical"]
reg_evolutions = [0, 1, 2, 3]
fos_evolutions = [0, 1, 2]
reg_types = ["Bug", "Custom", "Dark", "Dragon", "Electric", "Fairy", "Fighting", "Fighting", "Fire", "Flying", "Ghost", "Ground", "Grass", "Ice", "None", "Normal", "Poison", "Psychic", "Rock", "Steel", "Water"]
sec_types = ["Bug", "Custom", "Dark", "Dragon", "Electric", "Fairy", "Fighting", "Fighting", "Flying", "Ghost", "Ground", "Ice", "None", "Normal", "Poison", "Psychic", "Rock", "Steel"]
regular_x_factor = ["mega evolution", "additional form", "signature move", "signature ability", "new mechanic", "corrupted form"]
starter_types = ["Fire", "Grass", "Water"]

# Long Immutable Lists
gen_1 = ["Bulbasaur", 
"Ivysaur", 
"Venusaur", 
"VenusaurMega Venusaur", 
"Charmander", 
"Charmeleon", 
"Charizard", 
"CharizardMega Charizard X", 
"CharizardMega Charizard Y", 
"Squirtle", 
"Wartortle", 
"Blastoise", 
"BlastoiseMega Blastoise", 
"Caterpie", 
"Metapod", 
"Butterfree", 
"Weedle", 
"Kakuna", 
"Beedrill", 
"BeedrillMega Beedrill", 
"Pidgey", 
"Pidgeotto", 
"Pidgeot", 
"PidgeotMega Pidgeot", 
"Rattata", 
"Raticate", 
"Spearow", 
"Fearow", 
"Ekans", 
"Arbok", 
"Pikachu", 
"Raichu", 
"Sandshrew", 
"Sandslash", 
"Nidoran♀", 
"Nidorina", 
"Nidoqueen", 
"Nidoran♂", 
"Nidorino", 
"Nidoking", 
"Clefairy", 
"Clefable", 
"Vulpix", 
"Ninetales", 
"Jigglypuff", 
"Wigglytuff", 
"Zubat", 
"Golbat", 
"Oddish", 
"Gloom", 
"Vileplume", 
"Paras", 
"Parasect", 
"Venonat", 
"Venomoth", 
"Diglett", 
"Dugtrio", 
"Meowth", 
"Persian", 
"Psyduck", 
"Golduck", 
"Mankey", 
"Primeape", 
"Growlithe", 
"Arcanine", 
"Poliwag", 
"Poliwhirl", 
"Poliwrath", 
"Abra", 
"Kadabra", 
"Alakazam", 
"AlakazamMega Alakazam", 
"Machop", 
"Machoke", 
"Machamp", 
"Bellsprout", 
"Weepinbell", 
"Victreebel", 
"Tentacool", 
"Tentacruel", 
"Geodude", 
"Graveler", 
"Golem", 
"Ponyta", 
"Rapidash", 
"Slowpoke", 
"Slowbro", 
"SlowbroMega Slowbro", 
"Magnemite", 
"Magneton", 
"Farfetch'd", 
"Doduo", 
"Dodrio", 
"Seel", 
"Dewgong", 
"Grimer", 
"Muk", 
"Shellder", 
"Cloyster", 
"Gastly", 
"Haunter", 
"Gengar", 
"GengarMega Gengar", 
"Onix", 
"Drowzee", 
"Hypno", 
"Krabby", 
"Kingler", 
"Voltorb", 
"Electrode", 
"Exeggcute", 
"Exeggutor", 
"Cubone", 
"Marowak", 
"Hitmonlee", 
"Hitmonchan", 
"Lickitung", 
"Koffing", 
"Weezing", 
"Rhyhorn", 
"Rhydon", 
"Chansey", 
"Tangela", 
"Kangaskhan", 
"KangaskhanMega Kangaskhan", 
"Horsea", 
"Seadra", 
"Goldeen", 
"Seaking", 
"Staryu", 
"Starmie", 
"Mr. Mime", 
"Scyther", 
"Jynx", 
"Electabuzz", 
"Magmar", 
"Pinsir", 
"PinsirMega Pinsir", 
"Tauros", 
"Magikarp", 
"Gyarados", 
"GyaradosMega Gyarados", 
"Lapras", 
"Ditto", 
"Eevee", 
"Vaporeon", 
"Jolteon", 
"Flareon", 
"Porygon", 
"Omanyte", 
"Omastar", 
"Kabuto", 
"Kabutops", 
"Aerodactyl", 
"AerodactylMega Aerodactyl", 
"Snorlax", 
"Articuno", 
"Zapdos", 
"Moltres", 
"Dratini", 
"Dragonair", 
"Dragonite", 
"Mewtwo", 
"MewtwoMega Mewtwo X", 
"MewtwoMega Mewtwo Y", 
"Mew"]

gen_2 = ["Chikorita", 
"Bayleef", 
"Meganium", 
"Cyndaquil", 
"Quilava", 
"Typhlosion", 
"Totodile", 
"Croconaw", 
"Feraligatr", 
"Sentret", 
"Furret", 
"Hoothoot", 
"Noctowl", 
"Ledyba", 
"Ledian", 
"Spinarak", 
"Ariados", 
"Crobat", 
"Chinchou", 
"Lanturn", 
"Pichu", 
"Cleffa", 
"Igglybuff", 
"Togepi", 
"Togetic", 
"Natu", 
"Xatu", 
"Mareep", 
"Flaaffy", 
"Ampharos", 
"AmpharosMega Ampharos", 
"Bellossom", 
"Marill", 
"Azumarill", 
"Sudowoodo", 
"Politoed", 
"Hoppip", 
"Skiploom", 
"Jumpluff", 
"Aipom", 
"Sunkern", 
"Sunflora", 
"Yanma", 
"Wooper", 
"Quagsire", 
"Espeon", 
"Umbreon", 
"Murkrow", 
"Slowking", 
"Misdreavus", 
"Unown", 
"Wobbuffet", 
"Girafarig", 
"Pineco", 
"Forretress", 
"Dunsparce", 
"Gligar", 
"Steelix", 
"SteelixMega Steelix", 
"Snubbull", 
"Granbull", 
"Qwilfish", 
"Scizor", 
"ScizorMega Scizor", 
"Shuckle", 
"Heracross", 
"HeracrossMega Heracross", 
"Sneasel", 
"Teddiursa", 
"Ursaring", 
"Slugma", 
"Magcargo", 
"Swinub", 
"Piloswine", 
"Corsola", 
"Remoraid", 
"Octillery", 
"Delibird", 
"Mantine", 
"Skarmory", 
"Houndour", 
"Houndoom", 
"HoundoomMega Houndoom", 
"Kingdra", 
"Phanpy", 
"Donphan", 
"Porygon2", 
"Stantler", 
"Smeargle", 
"Tyrogue", 
"Hitmontop", 
"Smoochum", 
"Elekid", 
"Magby", 
"Miltank", 
"Blissey", 
"Raikou", 
"Entei", 
"Suicune", 
"Larvitar", 
"Pupitar", 
"Tyranitar", 
"TyranitarMega Tyranitar", 
"Lugia", 
"Ho-oh", 
"Celebi"]

gen_3 = ["Treecko", 
"Grovyle", 
"Sceptile", 
"SceptileMega Sceptile", 
"Torchic", 
"Combusken", 
"Blaziken", 
"BlazikenMega Blaziken", 
"Mudkip", 
"Marshtomp", 
"Swampert", 
"SwampertMega Swampert", 
"Poochyena", 
"Mightyena", 
"Zigzagoon", 
"Linoone", 
"Wurmple", 
"Silcoon", 
"Beautifly", 
"Cascoon", 
"Dustox", 
"Lotad", 
"Lombre", 
"Ludicolo", 
"Seedot", 
"Nuzleaf", 
"Shiftry", 
"Taillow", 
"Swellow", 
"Wingull", 
"Pelipper", 
"Ralts", 
"Kirlia", 
"Gardevoir", 
"GardevoirMega Gardevoir", 
"Surskit", 
"Masquerain", 
"Shroomish", 
"Breloom", 
"Slakoth", 
"Vigoroth", 
"Slaking", 
"Nincada", 
"Ninjask", 
"Shedinja", 
"Whismur", 
"Loudred", 
"Exploud", 
"Makuhita", 
"Hariyama", 
"Azurill", 
"Nosepass", 
"Skitty", 
"Delcatty", 
"Sableye", 
"SableyeMega Sableye", 
"Mawile", 
"MawileMega Mawile", 
"Aron", 
"Lairon", 
"Aggron", 
"AggronMega Aggron", 
"Meditite", 
"Medicham", 
"MedichamMega Medicham", 
"Electrike", 
"Manectric", 
"ManectricMega Manectric", 
"Plusle", 
"Minun", 
"Volbeat", 
"Illumise", 
"Roselia", 
"Gulpin", 
"Swalot", 
"Carvanha", 
"Sharpedo", 
"SharpedoMega Sharpedo", 
"Wailmer", 
"Wailord", 
"Numel", 
"Camerupt", 
"CameruptMega Camerupt", 
"Torkoal", 
"Spoink", 
"Grumpig", 
"Spinda", 
"Trapinch", 
"Vibrava", 
"Flygon", 
"Cacnea", 
"Cacturne", 
"Swablu", 
"Altaria", 
"AltariaMega Altaria", 
"Zangoose", 
"Seviper", 
"Lunatone", 
"Solrock", 
"Barboach", 
"Whiscash", 
"Corphish", 
"Crawdaunt", 
"Baltoy", 
"Claydol", 
"Lileep", 
"Cradily", 
"Anorith", 
"Armaldo", 
"Feebas", 
"Milotic", 
"Castform", 
"Kecleon", 
"Shuppet", 
"Banette", 
"BanetteMega Banette", 
"Duskull", 
"Dusclops", 
"Tropius", 
"Chimecho", 
"Absol", 
"AbsolMega Absol", 
"Wynaut", 
"Snorunt", 
"Glalie", 
"GlalieMega Glalie", 
"Spheal", 
"Sealeo", 
"Walrein", 
"Clamperl", 
"Huntail", 
"Gorebyss", 
"Relicanth", 
"Luvdisc", 
"Bagon", 
"Shelgon", 
"Salamence", 
"SalamenceMega Salamence", 
"Beldum", 
"Metang", 
"Metagross", 
"MetagrossMega Metagross", 
"Regirock", 
"Regice", 
"Registeel", 
"Latias", 
"LatiasMega Latias", 
"Latios", 
"LatiosMega Latios", 
"Kyogre", 
"KyogrePrimal Kyogre", 
"Groudon", 
"GroudonPrimal Groudon", 
"Rayquaza", 
"RayquazaMega Rayquaza", 
"Jirachi", 
"DeoxysNormal Forme", 
"DeoxysAttack Forme", 
"DeoxysDefense Forme", 
"DeoxysSpeed Forme"]

gen_4 = ["Turtwig", 
"Grotle", 
"Torterra", 
"Chimchar", 
"Monferno", 
"Infernape", 
"Piplup", 
"Prinplup", 
"Empoleon", 
"Starly", 
"Staravia", 
"Staraptor", 
"Bidoof", 
"Bibarel", 
"Kricketot", 
"Kricketune", 
"Shinx", 
"Luxio", 
"Luxray", 
"Budew", 
"Roserade", 
"Cranidos", 
"Rampardos", 
"Shieldon", 
"Bastiodon", 
"Burmy", 
"WormadamPlant Cloak", 
"WormadamSandy Cloak", 
"WormadamTrash Cloak", 
"Mothim", 
"Combee", 
"Vespiquen", 
"Pachirisu", 
"Buizel", 
"Floatzel", 
"Cherubi", 
"Cherrim", 
"Shellos", 
"Gastrodon", 
"Ambipom", 
"Drifloon", 
"Drifblim", 
"Buneary", 
"Lopunny", 
"LopunnyMega Lopunny", 
"Mismagius", 
"Honchkrow", 
"Glameow", 
"Purugly", 
"Chingling", 
"Stunky", 
"Skuntank", 
"Bronzor", 
"Bronzong", 
"Bonsly", 
"Mime Jr.", 
"Happiny", 
"Chatot", 
"Spiritomb", 
"Gible", 
"Gabite", 
"Garchomp", 
"GarchompMega Garchomp", 
"Munchlax", 
"Riolu", 
"Lucario", 
"LucarioMega Lucario", 
"Hippopotas", 
"Hippowdon", 
"Skorupi", 
"Drapion", 
"Croagunk", 
"Toxicroak", 
"Carnivine", 
"Finneon", 
"Lumineon", 
"Mantyke", 
"Snover", 
"Abomasnow", 
"AbomasnowMega Abomasnow", 
"Weavile", 
"Magnezone", 
"Lickilicky", 
"Rhyperior", 
"Tangrowth", 
"Electivire", 
"Magmortar", 
"Togekiss", 
"Yanmega", 
"Leafeon", 
"Glaceon", 
"Gliscor", 
"Mamoswine", 
"Porygon-Z", 
"Gallade", 
"GalladeMega Gallade", 
"Probopass", 
"Dusknoir", 
"Froslass", 
"Rotom", 
"RotomHeat Rotom", 
"RotomWash Rotom", 
"RotomFrost Rotom", 
"RotomFan Rotom", 
"RotomMow Rotom", 
"Uxie", 
"Mesprit", 
"Azelf", 
"Dialga", 
"Palkia", 
"Heatran", 
"Regigigas", 
"GiratinaAltered Forme", 
"GiratinaOrigin Forme", 
"Cresselia", 
"Phione", 
"Manaphy", 
"Darkrai", 
"ShayminLand Forme", 
"ShayminSky Forme", 
"Arceus"]

gen_5 = ["Victini", 
"Snivy", 
"Servine", 
"Serperior", 
"Tepig", 
"Pignite", 
"Emboar", 
"Oshawott", 
"Dewott", 
"Samurott", 
"Patrat", 
"Watchog", 
"Lillipup", 
"Herdier", 
"Stoutland", 
"Purrloin", 
"Liepard", 
"Pansage", 
"Simisage", 
"Pansear", 
"Simisear", 
"Panpour", 
"Simipour", 
"Munna", 
"Musharna", 
"Pidove", 
"Tranquill", 
"Unfezant", 
"Blitzle", 
"Zebstrika", 
"Roggenrola", 
"Boldore", 
"Gigalith", 
"Woobat", 
"Swoobat", 
"Drilbur", 
"Excadrill", 
"Audino", 
"AudinoMega Audino", 
"Timburr", 
"Gurdurr", 
"Conkeldurr", 
"Tympole", 
"Palpitoad", 
"Seismitoad", 
"Throh", 
"Sawk", 
"Sewaddle", 
"Swadloon", 
"Leavanny", 
"Venipede", 
"Whirlipede", 
"Scolipede", 
"Cottonee", 
"Whimsicott", 
"Petilil", 
"Lilligant", 
"Basculin", 
"Sandile", 
"Krokorok", 
"Krookodile", 
"Darumaka", 
"DarmanitanStandard Mode", 
"DarmanitanZen Mode", 
"Maractus", 
"Dwebble", 
"Crustle", 
"Scraggy", 
"Scrafty", 
"Sigilyph", 
"Yamask", 
"Cofagrigus", 
"Tirtouga", 
"Carracosta", 
"Archen", 
"Archeops", 
"Trubbish", 
"Garbodor", 
"Zorua", 
"Zoroark", 
"Minccino", 
"Cinccino", 
"Gothita", 
"Gothorita", 
"Gothitelle", 
"Solosis", 
"Duosion", 
"Reuniclus", 
"Ducklett", 
"Swanna", 
"Vanillite", 
"Vanillish", 
"Vanilluxe", 
"Deerling", 
"Sawsbuck", 
"Emolga", 
"Karrablast", 
"Escavalier", 
"Foongus", 
"Amoonguss", 
"Frillish", 
"Jellicent", 
"Alomomola", 
"Joltik", 
"Galvantula", 
"Ferroseed", 
"Ferrothorn", 
"Klink", 
"Klang", 
"Klinklang", 
"Tynamo", 
"Eelektrik", 
"Eelektross", 
"Elgyem", 
"Beheeyem", 
"Litwick", 
"Lampent", 
"Chandelure", 
"Axew", 
"Fraxure", 
"Haxorus", 
"Cubchoo", 
"Beartic", 
"Cryogonal", 
"Shelmet", 
"Accelgor", 
"Stunfisk", 
"Mienfoo", 
"Mienshao", 
"Druddigon", 
"Golett", 
"Golurk", 
"Pawniard", 
"Bisharp", 
"Bouffalant", 
"Rufflet", 
"Braviary", 
"Vullaby", 
"Mandibuzz", 
"Heatmor", 
"Durant", 
"Deino", 
"Zweilous", 
"Hydreigon", 
"Larvesta", 
"Volcarona", 
"Cobalion", 
"Terrakion", 
"Virizion", 
"TornadusIncarnate Forme", 
"TornadusTherian Forme", 
"ThundurusIncarnate Forme", 
"ThundurusTherian Forme", 
"Reshiram", 
"Zekrom", 
"LandorusIncarnate Forme", 
"LandorusTherian Forme", 
"Kyurem", 
"KyuremBlack Kyurem", 
"KyuremWhite Kyurem", 
"KeldeoOrdinary Forme", 
"KeldeoResolute Forme", 
"MeloettaAria Forme", 
"MeloettaPirouette Forme", 
"Genesect"]

gen_6 = ["Chespin", 
"Quilladin", 
"Chesnaught", 
"Fennekin", 
"Braixen", 
"Delphox", 
"Froakie", 
"Frogadier", 
"Greninja", 
"Bunnelby", 
"Diggersby", 
"Fletchling", 
"Fletchinder", 
"Talonflame", 
"Scatterbug", 
"Spewpa", 
"Vivillon", 
"Litleo", 
"Pyroar", 
"Flabébé", 
"Floette", 
"Florges", 
"Skiddo", 
"Gogoat", 
"Pancham", 
"Pangoro", 
"Furfrou", 
"Espurr", 
"MeowsticMale", 
"MeowsticFemale", 
"Honedge", 
"Doublade", 
"AegislashBlade Forme", 
"AegislashShield Forme", 
"Spritzee", 
"Aromatisse", 
"Swirlix", 
"Slurpuff", 
"Inkay", 
"Malamar", 
"Binacle", 
"Barbaracle", 
"Skrelp", 
"Dragalge", 
"Clauncher", 
"Clawitzer", 
"Helioptile", 
"Heliolisk", 
"Tyrunt", 
"Tyrantrum", 
"Amaura", 
"Aurorus", 
"Sylveon", 
"Hawlucha", 
"Dedenne", 
"Carbink", 
"Goomy", 
"Sliggoo", 
"Goodra", 
"Klefki", 
"Phantump", 
"Trevenant", 
"PumpkabooAverage Size", 
"PumpkabooSmall Size", 
"PumpkabooLarge Size", 
"PumpkabooSuper Size", 
"GourgeistAverage Size", 
"GourgeistSmall Size", 
"GourgeistLarge Size", 
"GourgeistSuper Size", 
"Bergmite", 
"Avalugg", 
"Noibat", 
"Noivern", 
"Xerneas", 
"Yveltal", 
"Zygarde50% Forme", 
"Diancie", 
"DiancieMega Diancie", 
"HoopaHoopa Confined", 
"HoopaHoopa Unbound", 
"Volcanion"]

gen_7 = ["Rattata", 
"Raticate", 
"Pikachu", 
"Raichu", 
"Sandshrew", 
"Sandslash", 
"Vulpix", 
"Ninetales", 
"Diglett", 
"Dugtrio", 
"Meowth", 
"Persian", 
"Geodude", 
"Graveler", 
"Golem", 
"Grimer", 
"Muk", 
"Exeggutor", 
"Marowak", 
"Eevee", 
"Greninja", 
"Zygarde10% Forme", 
"Zygarde", 
"Rowlet", 
"Dartrix", 
"Decidueye", 
"Litten", 
"Torracat", 
"Incineroar", 
"Popplio", 
"Brionne", 
"Primarina", 
"Pikipek", 
"Trumbeak", 
"Toucannon", 
"Yungoos", 
"Gumshoos", 
"Grubbin", 
"Charjabug", 
"Vikavolt", 
"Crabrawler", 
"Crabominable", 
"Oricorio", 
"Oricorio", 
"Oricorio", 
"Oricorio", 
"Cutiefly", 
"Ribombee", 
"Rockruff", 
"Rockruff", 
"Lycanroc", 
"Lycanroc", 
"Lycanroc", 
"Wishiwashi", 
"Wishiwashi", 
"Mareanie", 
"Toxapex", 
"Mudbray", 
"Mudsdale", 
"Dewpider", 
"Araquanid", 
"Fomantis", 
"Lurantis", 
"Morelull", 
"Shiinotic", 
"Salandit", 
"Salazzle", 
"Stufful", 
"Bewear", 
"Bounsweet", 
"Steenee", 
"Tsareena", 
"Comfey", 
"Oranguru", 
"Passimian", 
"Wimpod", 
"Golisopod", 
"Sandygast", 
"Palossand", 
"Pyukumuku", 
"Type: Null", 
"Silvally", 
"Minior", 
"Minior", 
"Komala", 
"Turtonator", 
"Togedemaru", 
"Mimikyu", 
"Bruxish", 
"Drampa", 
"Dhelmise", 
"Jangmo-o", 
"Hakamo-o", 
"Kommo-o", 
"Tapu Koko", 
"Tapu Lele", 
"Tapu Bulu", 
"Tapu Fini", 
"Cosmog", 
"Cosmoem", 
"Solgaleo", 
"Lunala", 
"Nihilego", 
"Buzzwole", 
"Pheromosa", 
"Xurkitree", 
"Celesteela", 
"Kartana", 
"Guzzlord", 
"Necrozma", 
"Necrozma", 
"Necrozma", 
"Necrozma", 
"Magearna", 
"Marshadow", 
"Poipole", 
"Naganadel", 
"Stakataka", 
"Blacephalon", 
"Zeraora", 
"Meltan", 
"Melmetal"]

gen_8 = ["Meowth", 
"Growlithe", 
"Arcanine", 
"Ponyta", 
"Rapidash", 
"Slowpoke", 
"Slowbro", 
"Farfetch'd", 
"Voltorb", 
"Electrode", 
"Weezing", 
"Mr. Mime", 
"Articuno", 
"Zapdos", 
"Moltres", 
"Typhlosion", 
"Slowking", 
"Qwilfish", 
"Sneasel", 
"Corsola", 
"Zigzagoon", 
"Linoone", 
"Dialga", 
"Palkia", 
"Samurott", 
"Lilligant", 
"Basculin", 
"Darumaka", 
"Darmanitan", 
"Darmanitan", 
"Yamask", 
"Zorua", 
"Zoroark", 
"Stunfisk", 
"Braviary", 
"Sliggoo", 
"Goodra", 
"Avalugg", 
"Decidueye", 
"Grookey", 
"Thwackey", 
"Rillaboom", 
"Scorbunny", 
"Raboot", 
"Cinderace", 
"Sobble", 
"Drizzile", 
"Inteleon", 
"Skwovet", 
"Greedent", 
"Rookidee", 
"Corvisquire", 
"Corviknight", 
"Blipbug", 
"Dottler", 
"Orbeetle", 
"Nickit", 
"Thievul", 
"Gossifleur", 
"Eldegoss", 
"Wooloo", 
"Dubwool", 
"Chewtle", 
"Drednaw", 
"Yamper", 
"Boltund", 
"Rolycoly", 
"Carkol", 
"Coalossal", 
"Applin", 
"Flapple", 
"Appletun", 
"Silicobra", 
"Sandaconda", 
"Cramorant", 
"Arrokuda", 
"Barraskewda", 
"Toxel", 
"Toxtricity", 
"Toxtricity", 
"Sizzlipede", 
"Centiskorch", 
"Clobbopus", 
"Grapploct", 
"Sinistea", 
"Polteageist", 
"Hatenna", 
"Hattrem", 
"Hatterene", 
"Impidimp", 
"Morgrem", 
"Grimmsnarl", 
"Obstagoon", 
"Perrserker", 
"Cursola", 
"Sirfetch'd", 
"Mr. Rime", 
"Runerigus", 
"Milcery", 
"Alcremie", 
"Falinks", 
"Pincurchin", 
"Snom", 
"Frosmoth", 
"Stonjourner", 
"Eiscue", 
"Eiscue", 
"Indeedee", 
"Indeedee", 
"Morpeko", 
"Morpeko", 
"Cufant", 
"Copperajah", 
"Dracozolt", 
"Arctozolt", 
"Dracovish", 
"Arctovish", 
"Duraludon", 
"Dreepy", 
"Drakloak", 
"Dragapult", 
"Zacian", 
"Zacian", 
"Zamazenta", 
"Zamazenta", 
"Eternatus", 
"Eternatus", 
"Kubfu", 
"Urshifu", 
"Urshifu", 
"Zarude", 
"Regieleki", 
"Regidrago", 
"Glastrier", 
"Spectrier", 
"Calyrex", 
"Calyrex", 
"Calyrex", 
"Wyrdeer", 
"Kleavor", 
"Ursaluna", 
"Basculegion", 
"Basculegion", 
"Sneasler", 
"Overqwil", 
"Enamorus", 
"Enamorus"]

gen_9 = ["Tauros", 
"Tauros", 
"Tauros", 
"Wooper", 
"Ursaluna", 
"Sprigatito", 
"Floragato", 
"Meowscarada", 
"Fuecoco", 
"Crocalor", 
"Skeledirge", 
"Quaxly", 
"Quaxwell", 
"Quaquaval", 
"Lechonk", 
"Oinkologne", 
"Oinkologne", 
"Tarountula", 
"Spidops", 
"Nymble", 
"Lokix", 
"Pawmi", 
"Pawmo", 
"Pawmot", 
"Tandemaus", 
"Maushold", 
"Maushold", 
"Fidough", 
"Dachsbun", 
"Smoliv", 
"Dolliv", 
"Arboliva", 
"Squawkabilly", 
"Squawkabilly", 
"Squawkabilly", 
"Squawkabilly", 
"Nacli", 
"Naclstack", 
"Garganacl", 
"Charcadet", 
"Armarouge", 
"Ceruledge", 
"Tadbulb", 
"Bellibolt", 
"Wattrel", 
"Kilowattrel", 
"Maschiff", 
"Mabosstiff", 
"Shroodle", 
"Grafaiai", 
"Bramblin", 
"Brambleghast", 
"Toedscool", 
"Toedscruel", 
"Klawf", 
"Capsakid", 
"Scovillain", 
"Rellor", 
"Rabsca", 
"Flittle", 
"Espathra", 
"Tinkatink", 
"Tinkatuff", 
"Tinkaton", 
"Wiglett", 
"Wugtrio", 
"Bombirdier", 
"Finizen", 
"Palafin", 
"Palafin", 
"Varoom", 
"Revavroom", 
"Cyclizar", 
"Orthworm", 
"Glimmet", 
"Glimmora", 
"Greavard", 
"Houndstone", 
"Flamigo", 
"Cetoddle", 
"Cetitan", 
"Veluza", 
"Dondozo", 
"Tatsugiri", 
"Tatsugiri", 
"Tatsugiri", 
"Annihilape", 
"Clodsire", 
"Farigiraf", 
"Dudunsparce", 
"Dudunsparce", 
"Kingambit", 
"Great Tusk", 
"Scream Tail", 
"Brute Bonnet", 
"Flutter Mane", 
"Slither Wing", 
"Sandy Shocks", 
"Iron Treads", 
"Iron Bundle", 
"Iron Hands", 
"Iron Jugulis", 
"Iron Moth", 
"Iron Thorns", 
"Frigibax", 
"Arctibax", 
"Baxcalibur", 
"Gimmighoul", 
"Gimmighoul", 
"Gholdengo", 
"Wo-Chien", 
"Chien-Pao", 
"Ting-Lu", 
"Chi-Yu", 
"Roaring Moon", 
"Iron Valiant", 
"Koraidon", 
"Miraidon", 
"Walking Wake", 
"Iron Leaves", 
"Dipplin", 
"Poltchageist", 
"Sinistcha", 
"Okidogi", 
"Munkidori", 
"Fezandipiti", 
"Ogerpon", 
"Ogerpon", 
"Ogerpon", 
"Ogerpon", 
"Archaludon", 
"Hydrapple", 
"Gouging Fire", 
"Raging Bolt", 
"Iron Boulder", 
"Iron Crown", 
"Terapagos", 
"Terapagos", 
"Terapagos", 
"Pecharunt"]


def ReturnGen1():
    return random.choice(gen_1)

def ReturnGen2():
    return random.choice(gen_2)

def ReturnGen3():
    return random.choice(gen_3)

def ReturnGen4():
    return random.choice(gen_4)

def ReturnGen5():
    return random.choice(gen_5)

def ReturnGen6():
    return random.choice(gen_6)

def ReturnGen7():
    return random.choice(gen_7)

def ReturnGen8():
    return random.choice(gen_8)

def ReturnGen9():
    return random.choice(gen_9)